//   
//   Project Name:        Kratos       
//   Last Modified by:    $Author:  $
//   Date:                $Date:  $
//   Revision:            $Revision: 1.3 $
//
// 



// System includes


// External includes 


// Project includes
#include "includes/define.h"
#include "geometries/point_2d.h" 
#include "geometries/line_3d_2.h"
#include "geometries/triangle_2d_3.h"
#include "geometries/triangle_3d_3.h"
#include "geometries/tetrahedra_3d_4.h"
#include "geometries/quadrilateral_2d_4.h"
#include "geometries/hexahedra_3d_8.h"
#include "multiphase_application.h"
#include "includes/variables.h"

using namespace std;

namespace Kratos
{
        KRATOS_CREATE_VARIABLE(int, IS_FLOW_STATIONARY)
        KRATOS_CREATE_VARIABLE(int, IS_TRANSPORT_STATIONARY)
        //KRATOS_CREATE_VARIABLE(int, IS_BUOYANCY)
           
		KRATOS_CREATE_VARIABLE(double, HEAD_LEVEL) // PERMEABILITY_WATER, DENSITY & CONCENTRATION ALREADY EXIST AT KERNEL
        KRATOS_CREATE_VARIABLE(double, SPECIFIC_STORAGE)
        	
        //KRATOS_CREATE_VARIABLE(double, SATURATION_WET)
        //KRATOS_CREATE_VARIABLE(double, PRESSURE_NON)
        //KRATOS_CREATE_VARIABLE(double, SATURATION_NON)
        //KRATOS_CREATE_VARIABLE(double, PRESSURE_WET)
        //KRATOS_CREATE_VARIABLE(double, POROSITY_ELEM)	
        //KRATOS_CREATE_VARIABLE(double, PERMEABILITY_ELEM)
        //KRATOS_CREATE_VARIABLE(double, PERMEABILITY_WET_ELEM)
        //KRATOS_CREATE_VARIABLE(double, PERMEABILITY_NON_ELEM)
        //KRATOS_CREATE_VARIABLE(double, VISCOSITY_WET_ELEM)
        //KRATOS_CREATE_VARIABLE(double, VISCOSITY_NON_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DENSITY_WET_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DENSITY_NON_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DIFFUSION_COEFFICIENT_ELEM)
        KRATOS_CREATE_VARIABLE(double, PERMEABILITY)
        KRATOS_CREATE_VARIABLE(double, DIFFUSION_COEFFICIENT)
        
        //KRATOS_CREATE_VARIABLE(int, IS_CAPILLARITY_NEGLECTED)
        //KRATOS_CREATE_VARIABLE(string, CAPILLARITY_PRESSURE_MODEL)
        //KRATOS_CREATE_VARIABLE(string, RELATIVE_PERMEABILITY_MODEL)
        //KRATOS_CREATE_VARIABLE(double, RESIDUAL_SW)
        //KRATOS_CREATE_VARIABLE(double, RESIDUAL_SN)
        //KRATOS_CREATE_VARIABLE(double, EXPONENT_KR_LAW)
        //KRATOS_CREATE_VARIABLE(double, LAMBDA_LEVERETT)
        //KRATOS_CREATE_VARIABLE(double, ENTRY_PRESSURE)
        
        //KRATOS_CREATE_VARIABLE(double, SATURATION_WET_ELEM)
        //KRATOS_CREATE_VARIABLE(double, CAPILLARITY_PRESSURE_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DERIV_PC_SW_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DERIV_2_PC_SW_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DERIV_KRW_SW_ELEM)
        //KRATOS_CREATE_VARIABLE(double, DERIV_KRN_SW_ELEM)
        
        
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE)
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE_PRESS)
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE_PHASE_SAT)
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE_PHASE_PRESS)
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE_PRESS_Z)
        KRATOS_CREATE_VARIABLE(double, SINK_SOURCE_HEIGHT)
        
        KRATOS_CREATE_VARIABLE(string, SV)
        KRATOS_CREATE_VARIABLE(string, SV_X)
        KRATOS_CREATE_VARIABLE(string, SV_Y)
        KRATOS_CREATE_VARIABLE(string, SV_Z)
        
        KRATOS_CREATE_VARIABLE(double, LEAKAGE_COEFFICIENT) 
        KRATOS_CREATE_VARIABLE(double, LEVEL)
        
        KRATOS_CREATE_VARIABLE(double, INPUT_FLOW)
        KRATOS_CREATE_VARIABLE(double, PRESCRIBED_VALUE)
        
        KRATOS_CREATE_VARIABLE(double, DENSITY_ELEM)
        KRATOS_CREATE_VARIABLE(double, DARCY_FLOW_X)
        KRATOS_CREATE_VARIABLE(double, DARCY_FLOW_Y)
        
        //KRATOS_CREATE_VARIABLE(double, ENTHALPY_WET_NODE)
        //KRATOS_CREATE_VARIABLE(double, ENTHALPY_NON_NODE)
        
        KRATOS_CREATE_VARIABLE(double, CONCENTRATION_OLD_IT)
		KRATOS_CREATE_VARIABLE(double, PRESSURE_OLD_IT )
		KRATOS_CREATE_VARIABLE(double, CONCENTRATION)
        KRATOS_CREATE_VARIABLE(double, FIRST_SV_OLD_IT)
        KRATOS_CREATE_VARIABLE(double, SECOND_SV_OLD_IT)

        
        KRATOS_CREATE_VARIABLE(double, STORAGE_BALANCE)
        KRATOS_CREATE_VARIABLE(double, DARCY_FLOW_BALANCE)
        KRATOS_CREATE_VARIABLE(double, SINKSOURCE_BALANCE)
        
        KRATOS_CREATE_VARIABLE(double, MAXDIFF_SV_1)
        KRATOS_CREATE_VARIABLE(double, MAXDIFF_SV_2)
        KRATOS_CREATE_VARIABLE(double, MAXITER_SV_1)
        KRATOS_CREATE_VARIABLE(double, MAXITER_SV_2)  
        KRATOS_CREATE_VARIABLE(double, MAXNORMREL_NR)
        KRATOS_CREATE_VARIABLE(double, MAXITER_NR)
        
        KRATOS_CREATE_VARIABLE(int, TIMES_TO_PRINT )    
        
 	KratosMultiphaseApplication::KratosMultiphaseApplication(): //constructor  do not forget to add the ":" 
		
                mFlowPressureTrans2D    ( 0, Element::GeometryType::Pointer(new Triangle2D3<Node<3> >(Element::GeometryType::PointsArrayType(3)))),
                
                mMultiphaseVE1D (0, Element::GeometryType::Pointer(new Line2D2<Node<3> >(Element::GeometryType::PointsArrayType(2)))),
                mMultiphaseVE2D (0, Element::GeometryType::Pointer(new Triangle2D3<Node<3> >(Element::GeometryType::PointsArrayType(3)))),
				mMultiphaseFEM1D(0, Element::GeometryType::Pointer(new Line2D2<Node<3> >(Element::GeometryType::PointsArrayType(2)))),
				mMultiphaseFEM2D (0, Element::GeometryType::Pointer(new Triangle2D3<Node<3> >(Element::GeometryType::PointsArrayType(3)))),
                
                mPointSinkSourcePressure( 0, Element::GeometryType::Pointer(new Point2D<Node<3> >( Element::GeometryType::PointsArrayType(1)))),
                mLineSinkSourcePressure( 0, Element::GeometryType::Pointer(new Line2D2<Node<3> >(Element::GeometryType::PointsArrayType(2)))),
                //mTriangleSinkSourcePressure( 0, Element::GeometryType::Pointer(new Triangle2D3<Node<3> >(Element::GeometryType::PointsArrayType(3)))),
                
                mPointSinkSourceNonVE( 0, Element::GeometryType::Pointer(new Point2D<Node<3> >( Element::GeometryType::PointsArrayType(1)))),
                mLineSinkSourceNonVE( 0, Element::GeometryType::Pointer(new Line2D2<Node<3> >(Element::GeometryType::PointsArrayType(2)))),
                
                mMassFlow ( 0, Element::GeometryType::Pointer(new Point2D<Node<3> >( Element::GeometryType::PointsArrayType(1)))),

                mMassFlowVE ( 0, Element::GeometryType::Pointer(new Point2D<Node<3> >( Element::GeometryType::PointsArrayType(1)))),
                mInterfaceVE_2 ( 0, Element::GeometryType::Pointer(new Point2D<Node<3> >( Element::GeometryType::PointsArrayType(1)))),
				mPointSinkSourceNonFEM(0, Element::GeometryType::Pointer(new Point2D<Node<3> >(Element::GeometryType::PointsArrayType(1)))),
				mLineSinkSourceNonFEM(0, Element::GeometryType::Pointer(new Line2D2<Node<3> >(Element::GeometryType::PointsArrayType(2))))
                {}      
        
	void KratosMultiphaseApplication::Register()
	{
		// calling base class register to register Kratos components
		KratosApplication::Register();
		std::cout << "Initializing KratosMultiphaseApplication... " << std::endl;
                
                KRATOS_REGISTER_VARIABLE(  IS_FLOW_STATIONARY )
                KRATOS_REGISTER_VARIABLE(  IS_TRANSPORT_STATIONARY )
                KRATOS_REGISTER_VARIABLE(  IS_BUOYANCY )
                KRATOS_REGISTER_VARIABLE( IS_TRANSIENT )  
                        
                KRATOS_REGISTER_VARIABLE(  HEAD_LEVEL )
                KRATOS_REGISTER_VARIABLE(  SPECIFIC_STORAGE )
		
                KRATOS_REGISTER_VARIABLE(SATURATION_WET)
                KRATOS_REGISTER_VARIABLE(PRESSURE_NON)
                KRATOS_REGISTER_VARIABLE(POROSITY_ELEM)
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_WET_ELEM)
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_NON_ELEM)
                KRATOS_REGISTER_VARIABLE(VISCOSITY_WET_ELEM)
                KRATOS_REGISTER_VARIABLE(VISCOSITY_NON_ELEM)
                KRATOS_REGISTER_VARIABLE(DENSITY_WET_ELEM)
                KRATOS_REGISTER_VARIABLE(DENSITY_NON_ELEM)
                KRATOS_REGISTER_VARIABLE( COMPRESSIBLITY_NON_ELEM ) 
                KRATOS_REGISTER_VARIABLE( COMPRESSIBLITY_WET_ELEM )
                KRATOS_REGISTER_VARIABLE( SPECIFIC_HEAT_NON_ELEM )
                KRATOS_REGISTER_VARIABLE( SPECIFIC_HEAT_WET_ELEM ) 
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_ELEM )
                KRATOS_REGISTER_VARIABLE( DIFFUSION_COEFFICIENT_ELEM )
                KRATOS_REGISTER_VARIABLE(PERMEABILITY)
                KRATOS_REGISTER_VARIABLE( DIFFUSION_COEFFICIENT )
                        
                KRATOS_REGISTER_VARIABLE(IS_CAPILLARITY_NEGLECTED)
                KRATOS_REGISTER_VARIABLE(CAPILLARITY_PRESSURE_MODEL)
                KRATOS_REGISTER_VARIABLE(RELATIVE_PERMEABILITY_MODEL)
                KRATOS_REGISTER_VARIABLE(RESIDUAL_SW)
                KRATOS_REGISTER_VARIABLE(RESIDUAL_SN)
                KRATOS_REGISTER_VARIABLE(EXPONENT_KR_LAW)
                KRATOS_REGISTER_VARIABLE(LAMBDA_LEVERETT)
                KRATOS_REGISTER_VARIABLE(ENTRY_PRESSURE)
                KRATOS_REGISTER_VARIABLE( CO2_EOS )
                KRATOS_REGISTER_VARIABLE( IS_COMPRESSIBLE )
                KRATOS_REGISTER_VARIABLE( IS_COMPRESSIBLE_NON_PHASE )
                KRATOS_REGISTER_VARIABLE( IS_COMPRESSIBLE_WET_PHASE )
                KRATOS_REGISTER_VARIABLE( IS_NONISOTHERMAL_NON)
                KRATOS_REGISTER_VARIABLE( IS_NONISOTHERMAL_WET)
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON )
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET )
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_NON_X_NODE )   
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_NON_Y_NODE )  
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_NON_Z_NODE ) 
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_WET_X_NODE )   
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_WET_Y_NODE )  
                KRATOS_REGISTER_VARIABLE( DARCYFLOW_WET_Z_NODE ) 
                KRATOS_REGISTER_VARIABLE( THERMALCONDUCTIVITY_NON_ELEM )
                KRATOS_REGISTER_VARIABLE( THERMALCONDUCTIVITY_WET_ELEM )
                KRATOS_REGISTER_VARIABLE( DENSITY_NON_NODE )
                KRATOS_REGISTER_VARIABLE( DENSITY_WET_NODE )
                KRATOS_REGISTER_VARIABLE( VISCOSITY_NON_NODE )
                KRATOS_REGISTER_VARIABLE( VISCOSITY_WET_NODE ) 
                        
                KRATOS_REGISTER_VARIABLE(SATURATION_WET_ELEM)
                KRATOS_REGISTER_VARIABLE(PRESSURE_NON_ELEM)
                KRATOS_REGISTER_VARIABLE(CAPILLARITY_PRESSURE_ELEM)
                KRATOS_REGISTER_VARIABLE(DERIV_PC_SW_ELEM)        
                KRATOS_REGISTER_VARIABLE(DERIV_2_PC_SW_ELEM)
                KRATOS_REGISTER_VARIABLE(DERIV_KRW_SW_ELEM)
                KRATOS_REGISTER_VARIABLE(DERIV_KRN_SW_ELEM)
                KRATOS_REGISTER_VARIABLE( DERIV_BETAN_PN_ELEM )
                KRATOS_REGISTER_VARIABLE( DERIV_BETAW_PW_ELEM )
                KRATOS_REGISTER_VARIABLE( DERIV_DENSITYNON_PN_ELEM )
                KRATOS_REGISTER_VARIABLE( DERIV_2_DENSITYNON_PN_ELEM )
                KRATOS_REGISTER_VARIABLE( DERIV_MUN_PN_ELEM )
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_WET_NODE)
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_NON_NODE) 
                KRATOS_REGISTER_VARIABLE(DERIV_PC_SW_NODE)
                KRATOS_REGISTER_VARIABLE(CAPILLARITY_PRESSURE_NODE)
                KRATOS_REGISTER_VARIABLE( COMPRESSIBLITY_NON_NODE ) 
                KRATOS_REGISTER_VARIABLE( COMPRESSIBLITY_WET_NODE )
                KRATOS_REGISTER_VARIABLE( SPECIFIC_HEAT_NON_NODE )
                KRATOS_REGISTER_VARIABLE( SPECIFIC_HEAT_WET_NODE )   
                KRATOS_REGISTER_VARIABLE( SINK_SOURCE_NON_ENTHALPY )
                        
                KRATOS_REGISTER_VARIABLE(DERIV_KRW_SW_NODE) 
                KRATOS_REGISTER_VARIABLE(DERIV_KRN_SW_NODE)
                KRATOS_REGISTER_VARIABLE(DERIV_2_PC_SW_NODE)
                KRATOS_REGISTER_VARIABLE( DERIV_BETAN_PW_NODE )
                KRATOS_REGISTER_VARIABLE( DERIV_BETAW_PW_NODE )
                KRATOS_REGISTER_VARIABLE( DERIV_DENSITYNON_PN_NODE )
                KRATOS_REGISTER_VARIABLE( DERIV_2_DENSITYNON_PN_NODE )
                KRATOS_REGISTER_VARIABLE( DERIV_MUN_PN_NODE )
                        
                KRATOS_REGISTER_VARIABLE( SV )
                KRATOS_REGISTER_VARIABLE( SV_X )
                KRATOS_REGISTER_VARIABLE( SV_Y )
                KRATOS_REGISTER_VARIABLE( SV_Z )
                     
                KRATOS_REGISTER_VARIABLE(  SINK_SOURCE )
                KRATOS_REGISTER_VARIABLE( SINK_SOURCE_PRESS )
                KRATOS_REGISTER_VARIABLE( SINK_SOURCE_PHASE_SAT )
                KRATOS_REGISTER_VARIABLE(  SINK_SOURCE_PHASE_PRESS  )
                KRATOS_REGISTER_VARIABLE(  SINK_SOURCE_PRESS_Z  )
                KRATOS_REGISTER_VARIABLE(  SINK_SOURCE_HEIGHT  )
                KRATOS_REGISTER_VARIABLE( SINK_SOURCE_NON )
                        
                KRATOS_REGISTER_VARIABLE( LEAKAGE_COEFFICIENT )
                KRATOS_REGISTER_VARIABLE( LEVEL )
                
                KRATOS_REGISTER_VARIABLE(  PRESCRIBED_VALUE )  
                
                KRATOS_REGISTER_VARIABLE( DENSITY_ELEM ) 
                KRATOS_REGISTER_VARIABLE( DARCY_FLOW_X )
                KRATOS_REGISTER_VARIABLE( DARCY_FLOW_Y )

                KRATOS_REGISTER_VARIABLE( ENTHALPY_WET_NODE )
                KRATOS_REGISTER_VARIABLE( ENTHALPY_NON_NODE )
                KRATOS_REGISTER_VARIABLE( ENTHALPY_WET_ELEM )
                KRATOS_REGISTER_VARIABLE( ENTHALPY_NON_ELEM )
                KRATOS_REGISTER_VARIABLE( TEMPERATURE_NODE )
                KRATOS_REGISTER_VARIABLE(TEMPERATURE_NON_NODE)
                KRATOS_REGISTER_VARIABLE(TEMPERATURE_WET_NODE)  
                KRATOS_REGISTER_VARIABLE( TEMPERATURE_ELEM )
                    
				KRATOS_REGISTER_VARIABLE( PRESSURE_OLD_IT )					
                KRATOS_REGISTER_VARIABLE( CONCENTRATION_OLD_IT )
				KRATOS_REGISTER_VARIABLE( CONCENTRATION )
                KRATOS_REGISTER_VARIABLE( FIRST_SV_OLD_IT )
                KRATOS_REGISTER_VARIABLE( SECOND_SV_OLD_IT )

                KRATOS_REGISTER_VARIABLE( STORAGE_BALANCE )
                KRATOS_REGISTER_VARIABLE( DARCY_FLOW_BALANCE )
                KRATOS_REGISTER_VARIABLE( SINKSOURCE_BALANCE ) 
                
                KRATOS_REGISTER_VARIABLE(MAXDIFF_SV_1)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_SV_2)
                KRATOS_REGISTER_VARIABLE(MAXITER_SV_1)
                KRATOS_REGISTER_VARIABLE(MAXITER_SV_2) 
                KRATOS_REGISTER_VARIABLE(MAXNORMREL_NR)
                KRATOS_REGISTER_VARIABLE(MAXITER_NR)
                KRATOS_REGISTER_VARIABLE(FIRST_SV_OLD_GLOBAL_IT)
                
                KRATOS_REGISTER_VARIABLE(MAXDIFF_PN)
                KRATOS_REGISTER_VARIABLE(MAXITER_PN)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_SW)
                KRATOS_REGISTER_VARIABLE(MAXITER_SW)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_PZ)
                KRATOS_REGISTER_VARIABLE(MAXITER_PZ)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_H)
                KRATOS_REGISTER_VARIABLE(MAXITER_H)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_HN)
                KRATOS_REGISTER_VARIABLE(MAXITER_HN)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_TW)
                KRATOS_REGISTER_VARIABLE(MAXITER_TW)
                KRATOS_REGISTER_VARIABLE(MAXDIFF_XN)
                KRATOS_REGISTER_VARIABLE(MAXITER_XN)
                KRATOS_REGISTER_VARIABLE(TEMPERATURE_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(TEMPERATURE_WET_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(ENTHALPY_NON_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(SATURATION_WET_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(PRESSURE_NON_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(IS_IMPES)
                        
                KRATOS_REGISTER_VARIABLE( TIMES_TO_PRINT )        
 
                //VE
                KRATOS_REGISTER_VARIABLE(PRESSURE_Z)
                KRATOS_REGISTER_VARIABLE(HEIGHT)
                KRATOS_REGISTER_VARIABLE(PRESSURE_Z_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(HEIGHT_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(HEIGHT_CORRECTED)
                KRATOS_REGISTER_VARIABLE(HEIGHT_ELEM)
                KRATOS_REGISTER_VARIABLE(THICKNESS_RESERVOIR)                      
                KRATOS_REGISTER_VARIABLE( MOBILITY_NON_NODE)
                KRATOS_REGISTER_VARIABLE( MOBILITY_WET_NODE)
                KRATOS_REGISTER_VARIABLE( MOBILITY_NON_ELEM)
                KRATOS_REGISTER_VARIABLE( MOBILITY_WET_ELEM)
                KRATOS_REGISTER_VARIABLE( MOBILITY_TOTAL_ELEM)
                KRATOS_REGISTER_VARIABLE( FRACTIONALFLOW_WET_ELEM)
                KRATOS_REGISTER_VARIABLE( FRACTIONALFLOW_NON_ELEM)
                KRATOS_REGISTER_VARIABLE( MOBILITY_TOTAL_NODE)
                KRATOS_REGISTER_VARIABLE( FRACTIONALFLOW_NON_NODE)
                KRATOS_REGISTER_VARIABLE( FRACTIONALFLOW_WET_NODE)
                KRATOS_REGISTER_VARIABLE( DERIV_FN_H_NODE)
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL )
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON_NODE ) 
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET_NODE )  
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL_NODE )
                KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_NODE )
                KRATOS_REGISTER_VARIABLE( STORAGE_SUM_BALANCE )
                KRATOS_REGISTER_VARIABLE( DARCY_FLOW_SUM_BALANCE )
                KRATOS_REGISTER_VARIABLE( SINKSOURCE_SUM_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIRICHLET_SUM_BALANCE)
                KRATOS_REGISTER_VARIABLE( NEUMANN_SUM_BALANCE)
                KRATOS_REGISTER_VARIABLE( STORAGE_PZ_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( STORAGE_ETA_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( ADVECTION_FRACT1_ETA_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( ADVECTION_FRACT2_ETA_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIFFUSION_ZT_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIFFUSION_ETA_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( SINKSOURCE_NON_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIRICHLET_NON_BALANCE)
                KRATOS_REGISTER_VARIABLE( NEUMANN_NON_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_NON_BALANCE)
                KRATOS_REGISTER_VARIABLE( STORAGE_PZ_WET_BALANCE )
                KRATOS_REGISTER_VARIABLE( STORAGE_ETA_WET_BALANCE )
                KRATOS_REGISTER_VARIABLE( ADVECTION_FRACT1_ETA_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE( ADVECTION_FRACT2_ETA_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE( DIFFUSION_ETA_WET_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIFFUSION_ZT_WET_BALANCE )
                KRATOS_REGISTER_VARIABLE( SINKSOURCE_WET_BALANCE )
                KRATOS_REGISTER_VARIABLE( DIRICHLET_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE( NEUMANN_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE(STORAGE_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE(ADVECTION_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE(SINKSOURCE_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( DIRICHLET_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( NEUMANN_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( STORAGE_SOLID_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( EXCHANGE_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISPERSION_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( CONDUCTION_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( CONDUCTION_SOLID_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_NON_ENTHALPY_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_WET_TEMP_BALANCE) 
                KRATOS_REGISTER_VARIABLE( STORAGE_SOLID_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( STORAGE_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( ADVECTION_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISPERSION_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( CONDUCTION_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( CONDUCTION_SOLID_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( SINKSOURCE_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DIRICHLET_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( NEUMANN_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( EXCHANGE_WET_TEMP_BALANCE)   
                KRATOS_REGISTER_VARIABLE( STORAGE_NON_COMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( ADVECTION_NON_COMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DIFFUSION_NON_COMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISPERSION_NON_COMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DIRICHLET_NON_COMP_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_NON_COMP_BALANCE) 
                        
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_SUM_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_NON_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_WET_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE( BRINE_LEAKAGE_WET_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_NON_ENTHALPY_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(EXCHANGE_NON_ENTHALPY_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(EXCHANGE_WET_TEMP_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_WET_TEMP_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_WET_TEMP_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_NON_COMP_BALANCE_PER_AREA) 
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_NON_COMP_BALANCE_PER_AREA) 
                        
                KRATOS_REGISTER_VARIABLE(N_NODES)
                KRATOS_REGISTER_VARIABLE(THETA)
                KRATOS_REGISTER_VARIABLE(PROPER_SIDE_X)
                KRATOS_REGISTER_VARIABLE(PROPER_SIDE_Y)
                KRATOS_REGISTER_VARIABLE(IS_BFECC)
                KRATOS_REGISTER_VARIABLE(IS_CONTROLLED_TIMESTEP) 
                KRATOS_REGISTER_VARIABLE(NON_COMPONENT_NODE)
                KRATOS_REGISTER_VARIABLE(NON_COMPONENT_OLD_ITER)
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_ON)
                KRATOS_REGISTER_VARIABLE(DISPERSIVITY_L)
                KRATOS_REGISTER_VARIABLE(DISPERSIVITY_T)
                KRATOS_REGISTER_VARIABLE(SPECIFIC_HEAT_SOLID_ELEM) 
                KRATOS_REGISTER_VARIABLE(THERMALCONDUCTIVITY_SOLID_ELEM)
                KRATOS_REGISTER_VARIABLE(DENSITY_SOLID_ELEM)
                KRATOS_REGISTER_VARIABLE(THERMALEXCHANGE_INTERFACE)
                KRATOS_REGISTER_VARIABLE(INTERFACE_THICKNESS)
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_ON)
                KRATOS_REGISTER_VARIABLE(CAPROCK_PERMEABILITY)
                KRATOS_REGISTER_VARIABLE(CAPROCK_THICKNESS)
                KRATOS_REGISTER_VARIABLE(CAPROCK_PRESSURE_NODE)
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_NON_COMP_BALANCE) 
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_WET_TEMP_BALANCE)
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_WET_BALANCE)
                KRATOS_REGISTER_VARIABLE(BRINE_LEAKAGE_SUM_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_SUM_BALANCE)
                KRATOS_REGISTER_VARIABLE( DISSOLUTION_SUM_BALANCE_PER_AREA)
                KRATOS_REGISTER_VARIABLE(NO_ITERATIVE)
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_REGIME)
                KRATOS_REGISTER_VARIABLE(ARRIVAL_TIME_DISSOLUTION)
                KRATOS_REGISTER_VARIABLE(DENSITY_WET_REF)
                KRATOS_REGISTER_VARIABLE(NON_COMPONENT_DUAN_NODE)
                KRATOS_REGISTER_VARIABLE(DENSITY_WET_DUAN_NODE)
                KRATOS_REGISTER_VARIABLE(NON_COMPONENT_DUAN)
                KRATOS_REGISTER_VARIABLE(DENSITY_WET_DUAN)
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_MODEL)
                KRATOS_REGISTER_VARIABLE(DISSOLUTION_FLUX_NODE)
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_Z_NODE)
                KRATOS_REGISTER_VARIABLE(DIFFUSION_COEFFICIENT_Z_NODE)
                KRATOS_REGISTER_VARIABLE(POROSITY_Z_NODE)
                KRATOS_REGISTER_VARIABLE(PERMEABILITY_Z_ELEM)
                KRATOS_REGISTER_VARIABLE(DIFFUSION_COEFFICIENT_Z_ELEM)
                KRATOS_REGISTER_VARIABLE(POROSITY_Z_ELEM)
                      
				//MultiphaseFEM
				KRATOS_REGISTER_VARIABLE(SATURATION_NON)
				KRATOS_REGISTER_VARIABLE(SATURATION_NON_ELEM)
				KRATOS_REGISTER_VARIABLE(SATURATION_NON_OLD_ITER)
				KRATOS_REGISTER_VARIABLE(PRESSURE_WET)
				KRATOS_REGISTER_VARIABLE(PRESSURE_WET_OLD_ITER)
				KRATOS_REGISTER_VARIABLE(DERIV_PC_SN_NODE);
				KRATOS_REGISTER_VARIABLE(DERIV_PC_SN_ELEM)
				KRATOS_REGISTER_VARIABLE(DERIV_FN_SN_ELEM)
				KRATOS_REGISTER_VARIABLE(COMPRESSIBILITY_MEDIUM_ELEM)
				KRATOS_REGISTER_VARIABLE(THERMAL_COEFF_NON_ELEM)
				KRATOS_REGISTER_VARIABLE(THERMAL_COEFF_WET_ELEM)

				KRATOS_REGISTER_VARIABLE(MAXDIFF_PW)
				KRATOS_REGISTER_VARIABLE(MAXITER_PW)
				KRATOS_REGISTER_VARIABLE(MAXDIFF_SN)
				KRATOS_REGISTER_VARIABLE(MAXITER_SN)
				KRATOS_REGISTER_VARIABLE(MAXDIFF_T)
				KRATOS_REGISTER_VARIABLE(MAXITER_T)

				KRATOS_REGISTER_VARIABLE(IS_NONCONSTANT_NON_PHASE)
				KRATOS_REGISTER_VARIABLE(IS_NONCONSTANT_WET_PHASE)

		// Registering elements and conditions here
                KRATOS_REGISTER_ELEMENT("FlowPressureTrans2D", mFlowPressureTrans2D);  //and here is our element
                KRATOS_REGISTER_ELEMENT("MultiphaseVE1D", mMultiphaseVE1D);
                KRATOS_REGISTER_ELEMENT("MultiphaseVE2D", mMultiphaseVE2D);
				KRATOS_REGISTER_ELEMENT("MultiphaseFEM1D", mMultiphaseFEM1D);
				KRATOS_REGISTER_ELEMENT("MultiphaseFEM2D", mMultiphaseFEM2D);
                
                KRATOS_REGISTER_CONDITION("PointSinkSourcePressure", mPointSinkSourcePressure);  //condition 2
                KRATOS_REGISTER_CONDITION("LineSinkSourcePressure", mLineSinkSourcePressure);  //condition 2 
                //KRATOS_REGISTER_CONDITION("TriangleSinkSourcePressure", mTriangleSinkSourcePressure);  //condition 2 
                        
                KRATOS_REGISTER_CONDITION("PointSinkSourceNonVE", mPointSinkSourceNonVE);  //condition 2
                KRATOS_REGISTER_CONDITION("LineSinkSourceNonVE", mLineSinkSourceNonVE);  //condition 2 
                
                KRATOS_REGISTER_CONDITION( "MassFlow", mMassFlow ); //condition 7

				KRATOS_REGISTER_CONDITION( "MassFlowVE", mMassFlowVE ); //condition 7
				
                KRATOS_REGISTER_CONDITION( "InterfaceVE_2", mInterfaceVE_2 ); //condition 7

				KRATOS_REGISTER_CONDITION("PointSinkSourceNonFEM", mPointSinkSourceNonFEM);  //condition 2
				KRATOS_REGISTER_CONDITION("LineSinkSourceNonFEM", mLineSinkSourceNonFEM);  //condition 2 
	}


}  // namespace Kratos.

