/*
==============================================================================
KratosFluidDynamicsApplication
A library based on:
Kratos
A General Purpose Software for Multi-Physics Finite Element Analysis

Copyright 2010
Pooyan Dadvand, Riccardo Rossi
pooyan@cimne.upc.edu
rrossi@cimne.upc.edu
- CIMNE (International Center for Numerical Methods in Engineering),
Gran Capita' s/n, 08034 Barcelona, Spain


Permission is hereby granted, free  of charge, to any person obtaining
a  copy  of this  software  and  associated  documentation files  (the
"Software"), to  deal in  the Software without  restriction, including
without limitation  the rights to  use, copy, modify,  merge, publish,
distribute,  sublicense and/or  sell copies  of the  Software,  and to
permit persons to whom the Software  is furnished to do so, subject to
the following condition:

Distribution of this code for  any  commercial purpose  is permissible
ONLY BY DIRECT ARRANGEMENT WITH THE COPYRIGHT OWNERS.

The  above  copyright  notice  and  this permission  notice  shall  be
included in all copies or substantial portions of the Software.

THE  SOFTWARE IS  PROVIDED  "AS  IS", WITHOUT  WARRANTY  OF ANY  KIND,
EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT  SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY
CLAIM, DAMAGES OR  OTHER LIABILITY, WHETHER IN AN  ACTION OF CONTRACT,
TORT  OR OTHERWISE, ARISING  FROM, OUT  OF OR  IN CONNECTION  WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

==============================================================================
*/

//
//   Project Name:        Kratos
//   Last Modified by:    $Author: VICbEZ $
//   Date:                $Date: 2010-11-11 $
//   Revision:            $Revision: 1.0 $
//
//


#if !defined(KRATOS_POROUS_MEDIA_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_POROUS_MEDIA_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes


// Project includes
#include "includes/define.h"
#include "includes/kratos_application.h"
#include "includes/variables.h"

namespace Kratos
{
//General
KRATOS_DEFINE_VARIABLE(double,SATURATION_WET)
KRATOS_DEFINE_VARIABLE(double,PRESSURE_NON)
KRATOS_DEFINE_VARIABLE(int,IS_CAPILLARITY_NEGLECTED)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_ELEM)
KRATOS_DEFINE_VARIABLE(double,VISCOSITY_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double,VISCOSITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_PC_SW_ELEM)
KRATOS_DEFINE_VARIABLE(double,DENSITY_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double,DENSITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double,COMPRESSIBLITY_NON_ELEM) 
KRATOS_DEFINE_VARIABLE(double,COMPRESSIBLITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double,SPECIFIC_HEAT_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double,SPECIFIC_HEAT_WET_ELEM) 
KRATOS_DEFINE_VARIABLE(double,POROSITY_ELEM)
KRATOS_DEFINE_VARIABLE(double,DIFFUSION_COEFFICIENT_ELEM)
KRATOS_DEFINE_VARIABLE(std::string,CO2_EOS)
KRATOS_DEFINE_VARIABLE(int,IS_COMPRESSIBLE)
KRATOS_DEFINE_VARIABLE(int,IS_COMPRESSIBLE_NON_PHASE)
KRATOS_DEFINE_VARIABLE(int,IS_COMPRESSIBLE_WET_PHASE)
KRATOS_DEFINE_VARIABLE(int,IS_NONISOTHERMAL_NON)
KRATOS_DEFINE_VARIABLE(int,IS_NONISOTHERMAL_WET)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON )
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_NON_X_NODE)   
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_NON_Y_NODE)  
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_NON_Z_NODE)  
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET )
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_WET_X_NODE)   
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_WET_Y_NODE)  
KRATOS_DEFINE_VARIABLE(double,DARCYFLOW_WET_Z_NODE)  
KRATOS_DEFINE_VARIABLE(double,THERMALCONDUCTIVITY_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double,THERMALCONDUCTIVITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double,SINK_SOURCE_NON_ENTHALPY)
KRATOS_DEFINE_VARIABLE(double, SINK_SOURCE_NON)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_PN)
KRATOS_DEFINE_VARIABLE(int,MAXITER_PN)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_SW)
KRATOS_DEFINE_VARIABLE(int,MAXITER_SW)
KRATOS_DEFINE_VARIABLE(double, MAXDIFF_PZ)
KRATOS_DEFINE_VARIABLE(int, MAXITER_PZ)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_H)
KRATOS_DEFINE_VARIABLE(int, MAXITER_H)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_HN)
KRATOS_DEFINE_VARIABLE(int,MAXITER_HN)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_TW)
KRATOS_DEFINE_VARIABLE(int,MAXITER_TW)
KRATOS_DEFINE_VARIABLE(double,MAXDIFF_XN)
KRATOS_DEFINE_VARIABLE(int,MAXITER_XN)
KRATOS_DEFINE_VARIABLE(int,IS_IMPES)
       
//General transport & flow, multiphase
KRATOS_DEFINE_VARIABLE(int, IS_TRANSIENT)
KRATOS_DEFINE_VARIABLE(int, IS_BUOYANCY)
        
//NR
KRATOS_DEFINE_VARIABLE(double,SATURATION_WET_ELEM)
KRATOS_DEFINE_VARIABLE( double,PRESSURE_NON_ELEM )
KRATOS_DEFINE_VARIABLE(double, ENTHALPY_WET_NODE )
KRATOS_DEFINE_VARIABLE(double, ENTHALPY_NON_NODE )
KRATOS_DEFINE_VARIABLE(double, ENTHALPY_WET_ELEM )
KRATOS_DEFINE_VARIABLE(double, ENTHALPY_NON_ELEM )
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_NODE)
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_NON_NODE)
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_WET_NODE)        
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_ELEM)
KRATOS_DEFINE_VARIABLE(double,RESIDUAL_SW)
KRATOS_DEFINE_VARIABLE(double,RESIDUAL_SN)
KRATOS_DEFINE_VARIABLE(double,DERIV_KRW_SW_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_KRN_SW_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_BETAN_PN_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_BETAW_PW_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_DENSITYNON_PN_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_2_DENSITYNON_PN_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_MUN_PN_ELEM)
KRATOS_DEFINE_VARIABLE(double,CAPILLARITY_PRESSURE_ELEM)
KRATOS_DEFINE_VARIABLE(double,DERIV_2_PC_SW_ELEM)
KRATOS_DEFINE_VARIABLE(std::string,RELATIVE_PERMEABILITY_MODEL)
KRATOS_DEFINE_VARIABLE(std::string,CAPILLARITY_PRESSURE_MODEL)
KRATOS_DEFINE_VARIABLE(double,EXPONENT_KR_LAW)
KRATOS_DEFINE_VARIABLE(double,LAMBDA_LEVERETT)
KRATOS_DEFINE_VARIABLE(double,ENTRY_PRESSURE)
KRATOS_DEFINE_VARIABLE(double,DENSITY_NON_NODE)
KRATOS_DEFINE_VARIABLE(double,DENSITY_WET_NODE)
KRATOS_DEFINE_VARIABLE(double,FIRST_SV_OLD_GLOBAL_IT)

//VE
KRATOS_DEFINE_VARIABLE(double,PRESSURE_Z)
KRATOS_DEFINE_VARIABLE(double,HEIGHT)
KRATOS_DEFINE_VARIABLE(double,PRESSURE_Z_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double,HEIGHT_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double, HEIGHT_CORRECTED)
KRATOS_DEFINE_VARIABLE(double,HEIGHT_ELEM)       
KRATOS_DEFINE_VARIABLE(double,THICKNESS_RESERVOIR)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_NON_NODE)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_WET_NODE)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_TOTAL_NODE)
KRATOS_DEFINE_VARIABLE(double, FRACTIONALFLOW_NON_NODE)
KRATOS_DEFINE_VARIABLE(double, FRACTIONALFLOW_WET_NODE)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double, MOBILITY_TOTAL_ELEM)
KRATOS_DEFINE_VARIABLE(double, FRACTIONALFLOW_WET_ELEM)
KRATOS_DEFINE_VARIABLE(double, FRACTIONALFLOW_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double, DERIV_FN_H_NODE)
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL )
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON_NODE ) 
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET_NODE )  
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL_NODE )
KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_NODE )
KRATOS_DEFINE_VARIABLE(double, STORAGE_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DARCY_FLOW_BALANCE) 
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DARCY_FLOW_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, NEUMANN_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_SUM_BALANCE) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_SUM_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_SUM_BALANCE_PER_AREA)
KRATOS_DEFINE_VARIABLE(double, STORAGE_PZ_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_ETA_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_FRACT1_ETA_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_FRACT2_ETA_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIFFUSION_ZT_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIFFUSION_ETA_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, NEUMANN_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_PZ_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_ETA_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_FRACT1_ETA_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_FRACT2_ETA_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIFFUSION_ETA_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIFFUSION_ZT_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, NEUMANN_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_WET_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, NEUMANN_NON_ENTHALPY_BALANCE)

KRATOS_DEFINE_VARIABLE(double, STORAGE_SOLID_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, EXCHANGE_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISPERSION_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, CONDUCTION_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, CONDUCTION_SOLID_NON_ENTHALPY_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_ENTHALPY_BALANCE)

KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_WET_TEMP_BALANCE)        
KRATOS_DEFINE_VARIABLE(double, STORAGE_SOLID_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, STORAGE_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISPERSION_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, CONDUCTION_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, CONDUCTION_SOLID_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, SINKSOURCE_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, NEUMANN_WET_TEMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, EXCHANGE_WET_TEMP_BALANCE)   
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_WET_TEMP_BALANCE)
        
KRATOS_DEFINE_VARIABLE(double, STORAGE_NON_COMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, ADVECTION_NON_COMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIFFUSION_NON_COMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISPERSION_NON_COMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DIRICHLET_NON_COMP_BALANCE)
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_COMP_BALANCE)  
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_NON_COMP_BALANCE) 

KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_SUM_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_WET_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_WET_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_ENTHALPY_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, EXCHANGE_NON_ENTHALPY_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, EXCHANGE_WET_TEMP_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_WET_TEMP_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_WET_TEMP_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, DISSOLUTION_NON_COMP_BALANCE_PER_AREA) 
KRATOS_DEFINE_VARIABLE(double, BRINE_LEAKAGE_NON_COMP_BALANCE_PER_AREA) 
        
KRATOS_DEFINE_VARIABLE(double, N_NODES)
KRATOS_DEFINE_VARIABLE(double, THETA)
KRATOS_DEFINE_VARIABLE(double, PROPER_SIDE_X)
KRATOS_DEFINE_VARIABLE(double, PROPER_SIDE_Y)
KRATOS_DEFINE_VARIABLE(int,IS_BFECC)
KRATOS_DEFINE_VARIABLE(int,IS_CONTROLLED_TIMESTEP) 
KRATOS_DEFINE_VARIABLE(double, NON_COMPONENT_NODE)
KRATOS_DEFINE_VARIABLE(double, NON_COMPONENT_OLD_ITER)
KRATOS_DEFINE_VARIABLE(int,DISSOLUTION_ON)
KRATOS_DEFINE_VARIABLE(double, DISPERSIVITY_L)
KRATOS_DEFINE_VARIABLE(double, DISPERSIVITY_T)
KRATOS_DEFINE_VARIABLE(double,SPECIFIC_HEAT_SOLID_ELEM) 
KRATOS_DEFINE_VARIABLE(double,THERMALCONDUCTIVITY_SOLID_ELEM)
KRATOS_DEFINE_VARIABLE(double,DENSITY_SOLID_ELEM)
KRATOS_DEFINE_VARIABLE(double,THERMALEXCHANGE_INTERFACE)
KRATOS_DEFINE_VARIABLE(double,INTERFACE_THICKNESS)
KRATOS_DEFINE_VARIABLE(int,BRINE_LEAKAGE_ON);
KRATOS_DEFINE_VARIABLE(double,CAPROCK_PERMEABILITY)
KRATOS_DEFINE_VARIABLE(double,CAPROCK_THICKNESS)
KRATOS_DEFINE_VARIABLE(double,CAPROCK_PRESSURE_NODE)
KRATOS_DEFINE_VARIABLE(int,NO_ITERATIVE)
KRATOS_DEFINE_VARIABLE(double,DISSOLUTION_REGIME)
KRATOS_DEFINE_VARIABLE(double,ARRIVAL_TIME_DISSOLUTION)
KRATOS_DEFINE_VARIABLE(double,DENSITY_WET_REF)
KRATOS_DEFINE_VARIABLE(double,NON_COMPONENT_DUAN_NODE)
KRATOS_DEFINE_VARIABLE(double,DENSITY_WET_DUAN_NODE)
KRATOS_DEFINE_VARIABLE(double,NON_COMPONENT_DUAN)
KRATOS_DEFINE_VARIABLE(double,DENSITY_WET_DUAN)
KRATOS_DEFINE_VARIABLE(std::string,DISSOLUTION_MODEL)
KRATOS_DEFINE_VARIABLE(double,DISSOLUTION_FLUX_NODE)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_Z_NODE)
KRATOS_DEFINE_VARIABLE(double,DIFFUSION_COEFFICIENT_Z_NODE)
KRATOS_DEFINE_VARIABLE(double,POROSITY_Z_NODE)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_Z_ELEM)
KRATOS_DEFINE_VARIABLE(double,DIFFUSION_COEFFICIENT_Z_ELEM)
KRATOS_DEFINE_VARIABLE(double,POROSITY_Z_ELEM)
        
//Isoparametric
KRATOS_DEFINE_VARIABLE(double,VISCOSITY_NON_NODE)
KRATOS_DEFINE_VARIABLE(double,VISCOSITY_WET_NODE)        
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_WET_NODE)
KRATOS_DEFINE_VARIABLE(double,PERMEABILITY_NON_NODE) 
KRATOS_DEFINE_VARIABLE(double,DERIV_PC_SW_NODE)
KRATOS_DEFINE_VARIABLE(double,CAPILLARITY_PRESSURE_NODE)
KRATOS_DEFINE_VARIABLE(double,COMPRESSIBLITY_NON_NODE) 
KRATOS_DEFINE_VARIABLE(double,COMPRESSIBLITY_WET_NODE)
KRATOS_DEFINE_VARIABLE(double,SPECIFIC_HEAT_NON_NODE)
KRATOS_DEFINE_VARIABLE(double,SPECIFIC_HEAT_WET_NODE)
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double,TEMPERATURE_WET_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double,ENTHALPY_NON_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double,SATURATION_WET_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double,PRESSURE_NON_OLD_ITER)
   
//IsoparametricNR
KRATOS_DEFINE_VARIABLE(double,DERIV_KRW_SW_NODE) 
KRATOS_DEFINE_VARIABLE(double,DERIV_KRN_SW_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_2_PC_SW_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_BETAN_PW_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_BETAW_PW_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_DENSITYNON_PN_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_2_DENSITYNON_PN_NODE)
KRATOS_DEFINE_VARIABLE(double,DERIV_MUN_PN_NODE)

//MultiphaseFEM
KRATOS_DEFINE_VARIABLE(double, PRESSURE_WET)
KRATOS_DEFINE_VARIABLE(double, PRESSURE_WET_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double, SATURATION_NON)
KRATOS_DEFINE_VARIABLE(double, SATURATION_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double, SATURATION_NON_OLD_ITER)
KRATOS_DEFINE_VARIABLE(double, DERIV_PC_SN_NODE);
KRATOS_DEFINE_VARIABLE(double, DERIV_PC_SN_ELEM)
KRATOS_DEFINE_VARIABLE(double, DERIV_FN_SN_ELEM)
KRATOS_DEFINE_VARIABLE(double, COMPRESSIBILITY_MEDIUM_ELEM)
KRATOS_DEFINE_VARIABLE(double, THERMAL_COEFF_NON_ELEM)
KRATOS_DEFINE_VARIABLE(double, THERMAL_COEFF_WET_ELEM)

KRATOS_DEFINE_VARIABLE(double, MAXDIFF_PW)
KRATOS_DEFINE_VARIABLE(int, MAXITER_PW)
KRATOS_DEFINE_VARIABLE(double, MAXDIFF_SN)
KRATOS_DEFINE_VARIABLE(int, MAXITER_SN)
KRATOS_DEFINE_VARIABLE(double, MAXDIFF_T)
KRATOS_DEFINE_VARIABLE(int, MAXITER_T)

KRATOS_DEFINE_VARIABLE(int, IS_NONCONSTANT_NON_PHASE)
KRATOS_DEFINE_VARIABLE(int, IS_NONCONSTANT_WET_PHASE)
        
}

#endif	/* KRATOS_POROUS_MEDIA_APPLICATION_VARIABLES_H_INCLUDED */

