/*
==============================================================================
KratosMultiphaseApplication 
A library based on:
Kratos
A General Purpose Software for Multi-Physics Finite Element Analysis
Version 1.0 (Released on march 05, 2007).

Copyright 2007
Pooyan Dadvand, Riccardo Rossi, Janosch Stascheit, Felix Nagel 
pooyan@cimne.upc.edu 
rrossi@cimne.upc.edu
janosch.stascheit@rub.de
nagel@sd.rub.de
- CIMNE (International Center for Numerical Methods in Engineering),
Gran Capita' s/n, 08034 Barcelona, Spain
- Ruhr-University Bochum, Institute for Structural Mechanics, Germany


Permission is hereby granted, free  of charge, to any person obtaining
a  copy  of this  software  and  associated  documentation files  (the
"Software"), to  deal in  the Software without  restriction, including
without limitation  the rights to  use, copy, modify,  merge, publish,
distribute,  sublicense and/or  sell copies  of the  Software,  and to
permit persons to whom the Software  is furnished to do so, subject to
the following condition:

Distribution of this code for  any  commercial purpose  is permissible
ONLY BY DIRECT ARRANGEMENT WITH THE COPYRIGHT OWNERS.

The  above  copyright  notice  and  this permission  notice  shall  be
included in all copies or substantial portions of the Software.

THE  SOFTWARE IS  PROVIDED  "AS  IS", WITHOUT  WARRANTY  OF ANY  KIND,
EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT  SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY
CLAIM, DAMAGES OR  OTHER LIABILITY, WHETHER IN AN  ACTION OF CONTRACT,
TORT  OR OTHERWISE, ARISING  FROM, OUT  OF OR  IN CONNECTION  WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

==============================================================================
*/
 
//   
//   Project Name:        Kratos       
//   Last modified by:    $Author:  VictorBez $
//   Date:                $Date: 2015 $
//   Revision:            $Revision: 1.0 $
//
//

// System includes 

#if defined(KRATOS_PYTHON)
// External includes 
#include <boost/python.hpp>

// Project includes
#include "includes/define.h"
#include "multiphase_application.h"
#include "custom_python/add_custom_strategies_to_python.h"
#include "custom_python/add_custom_utilities_to_python.h"


 
namespace Kratos
{

namespace Python
{

  using namespace boost::python;


  
  BOOST_PYTHON_MODULE(KratosMultiphaseApplication)
  {

    class_<KratosMultiphaseApplication,
           KratosMultiphaseApplication::Pointer,
           bases<KratosApplication>, boost::noncopyable >("KratosMultiphaseApplication")
           ;
    
    AddCustomStrategiesToPython();
    AddCustomUtilitiesToPython();
    
	//registering variables in python    
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_FLOW_STATIONARY);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_TRANSPORT_STATIONARY);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_BUOYANCY);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_TRANSIENT );  
                
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEAD_LEVEL);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SPECIFIC_STORAGE);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_WET);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_NON);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(POROSITY_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(VISCOSITY_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(VISCOSITY_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( COMPRESSIBLITY_NON_ELEM ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( COMPRESSIBLITY_WET_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPECIFIC_HEAT_NON_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPECIFIC_HEAT_WET_ELEM ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_COEFFICIENT_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_COEFFICIENT );
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_CAPILLARITY_NEGLECTED);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPILLARITY_PRESSURE_MODEL);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(RELATIVE_PERMEABILITY_MODEL);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(RESIDUAL_SW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(RESIDUAL_SN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(EXPONENT_KR_LAW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(LAMBDA_LEVERETT);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTRY_PRESSURE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CO2_EOS );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_COMPRESSIBLE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_COMPRESSIBLE_NON_PHASE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_COMPRESSIBLE_WET_PHASE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_NONISOTHERMAL_NON );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_NONISOTHERMAL_WET );
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON );
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_NON_X_NODE );   
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_NON_Y_NODE );  
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_NON_Z_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_WET_X_NODE );   
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_WET_Y_NODE );  
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCYFLOW_WET_Z_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( THERMALCONDUCTIVITY_NON_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( THERMALCONDUCTIVITY_WET_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY_NON_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY_WET_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY_NON_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY_WET_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NON_COMPONENT_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(NON_COMPONENT_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_ON );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISPERSIVITY_L);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISPERSIVITY_T);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SPECIFIC_HEAT_SOLID_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(THERMALCONDUCTIVITY_SOLID_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_SOLID_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(THERMALEXCHANGE_INTERFACE); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(INTERFACE_THICKNESS);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_ON);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPROCK_PERMEABILITY);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPROCK_THICKNESS);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPROCK_PRESSURE_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_NON_COMP_BALANCE); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_SUM_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_SUM_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_SUM_BALANCE_PER_AREA);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(NO_ITERATIVE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_REGIME);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ARRIVAL_TIME_DISSOLUTION);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_WET_REF);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(NON_COMPONENT_DUAN_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_WET_DUAN_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(NON_COMPONENT_DUAN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DENSITY_WET_DUAN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_MODEL);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_FLUX_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_Z_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DIFFUSION_COEFFICIENT_Z_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(POROSITY_Z_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_Z_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DIFFUSION_COEFFICIENT_Z_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(POROSITY_Z_ELEM);
                        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_NON_ELEM); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPILLARITY_PRESSURE_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_PC_SW_ELEM);        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_2_PC_SW_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_KRW_SW_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_KRN_SW_ELEM); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_BETAN_PN_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_BETAW_PW_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_DENSITYNON_PN_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_2_DENSITYNON_PN_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_MUN_PN_ELEM );
                
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_WET_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PERMEABILITY_NON_NODE); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_PC_SW_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(CAPILLARITY_PRESSURE_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( COMPRESSIBLITY_NON_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( COMPRESSIBLITY_WET_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPECIFIC_HEAT_NON_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPECIFIC_HEAT_WET_NODE ); 
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_KRW_SW_NODE); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_KRN_SW_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_2_PC_SW_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_BETAN_PW_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_BETAW_PW_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_DENSITYNON_PN_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_2_DENSITYNON_PN_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DERIV_MUN_PN_NODE );
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SV);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SV_X);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SV_Y);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SV_Z);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_PRESS);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_PHASE_SAT);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_PHASE_PRESS); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_PRESS_Z);  
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_HEIGHT);  
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(LEAKAGE_COEFFICIENT);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(LEVEL);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINK_SOURCE_NON);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESCRIBED_VALUE);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY_ELEM );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCY_FLOW_X );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCY_FLOW_Y );
	
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY_WET_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY_NON_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( TEMPERATURE_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(TEMPERATURE_NON_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(TEMPERATURE_WET_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( TEMPERATURE_ELEM );
        
		KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESSURE_OLD_IT );		
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONCENTRATION_OLD_IT );
		KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONCENTRATION );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIRST_SV_OLD_IT );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SECOND_SV_OLD_IT );
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_BALANCE ); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCY_FLOW_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINKSOURCE_BALANCE );

        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINK_SOURCE_NON_ENTHALPY );
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_SV_1);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_SV_2);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_SV_1);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_SV_2); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXNORMREL_NR);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_NR);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(FIRST_SV_OLD_GLOBAL_IT);          
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_IMPES);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_PN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_PN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_SW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_SW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_PZ);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_PZ);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_H);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_H);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_HN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_HN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_TW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_TW);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_XN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_XN);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(TEMPERATURE_WET_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(TEMPERATURE_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY_NON_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_WET_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_NON_OLD_ITER);
        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( TIMES_TO_PRINT );
        
        //VE
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_Z);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEIGHT);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_Z_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEIGHT_OLD_ITER);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEIGHT_CORRECTED);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEIGHT_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(THICKNESS_RESERVOIR);        
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_NON_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_WET_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_TOTAL_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(FRACTIONALFLOW_NON_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(FRACTIONALFLOW_WET_NODE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(MOBILITY_TOTAL_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(FRACTIONALFLOW_WET_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(FRACTIONALFLOW_NON_ELEM);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_FN_H_NODE);
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL ); 
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_NON_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_WET_NODE ); 
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DARCYFLOW_TOTAL_NODE );
        KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_NODE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_SUM_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DARCY_FLOW_SUM_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINKSOURCE_SUM_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_SUM_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEUMANN_SUM_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_PZ_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_ETA_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_FRACT1_ETA_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_FRACT2_ETA_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_ZT_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_ETA_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINKSOURCE_NON_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_NON_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEUMANN_NON_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_NON_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_PZ_WET_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_ETA_WET_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_FRACT1_ETA_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_FRACT2_ETA_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_ETA_WET_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_ZT_WET_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINKSOURCE_WET_BALANCE );
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEUMANN_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_WET_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(STORAGE_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(ADVECTION_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(SINKSOURCE_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEUMANN_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_SOLID_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXCHANGE_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISPERSION_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONDUCTION_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONDUCTION_SOLID_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_NON_ENTHALPY_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_SOLID_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISPERSION_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONDUCTION_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONDUCTION_SOLID_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( SINKSOURCE_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEUMANN_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXCHANGE_WET_TEMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( STORAGE_NON_COMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADVECTION_NON_COMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIFFUSION_NON_COMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISPERSION_NON_COMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIRICHLET_NON_COMP_BALANCE);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISSOLUTION_NON_COMP_BALANCE);  
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_SUM_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_NON_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_WET_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( BRINE_LEAKAGE_WET_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_NON_ENTHALPY_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(EXCHANGE_NON_ENTHALPY_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(EXCHANGE_WET_TEMP_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_WET_TEMP_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_WET_TEMP_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(DISSOLUTION_NON_COMP_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(BRINE_LEAKAGE_NON_COMP_BALANCE_PER_AREA); 
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(N_NODES);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( THETA);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( PROPER_SIDE_X);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( PROPER_SIDE_Y);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_BFECC);
        KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_CONTROLLED_TIMESTEP); 

		//MultiphaseFEM
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_NON);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_NON_ELEM);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(SATURATION_NON_OLD_ITER);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_WET);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSURE_WET_OLD_ITER);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_PC_SN_NODE);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_PC_SN_ELEM);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(DERIV_FN_SN_ELEM);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(COMPRESSIBILITY_MEDIUM_ELEM);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(THERMAL_COEFF_NON_ELEM);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(THERMAL_COEFF_WET_ELEM);

		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_PW);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_PW);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_SN);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_SN);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXDIFF_T);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXITER_T);

		KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_NONCONSTANT_NON_PHASE);
		KRATOS_REGISTER_IN_PYTHON_VARIABLE(IS_NONCONSTANT_WET_PHASE);
  }
  
  
}  // namespace Python.
  
}  // namespace Kratos.

#endif // KRATOS_PYTHON defined
